GET http://localhost:3003/api/blogs

###
GET http://localhost:3003/api/blogs/648e6a1e029ebac163c27823

###
POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{   "title": "TestTitle2",
    "author": "TestAuthor2",
    "url": "TestURL",
    "likes": 100
}

###
DELETE http://localhost:3003/api/blogs/648fbf425b8d7c7668b072ad HTTP/1.1

###
PUT http://localhost:3003/api/blogs/648e6a1e029ebac163c27823 HTTP/1.1
content-type: application/json

{   "title": "newTitle"
}

###
POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{
    "author": "TestAuthor2",
    "url": "TestURL",
    "likes": 100
}